services:
  as-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./data/as-router:/data # `init.sh` location
    networks:
      # networks attached to the container
      as:
        # `as` network defined in the `networks` section below
        ipv4_address: 120.0.16.2 # static IP

  irc-server:
    image: ergochat/ergo:latest
    networks:
      as:
        ipv4_address: 120.0.16.10

  matrix-server:
    image: matrixdotorg/synapse:latest
    environment:
      - SYNAPSE_SERVER_NAME=AS1
      - SYNAPSE_REPORT_STATS=yes
    # command: generate   # uncomment to generate config
    # to register users: 
    # docker compose exec matrix-server register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml
    volumes:
      - matrix-server:/data
    networks:
      as:
        ipv4_address: 120.0.16.11

  matrix-web:
    image: vectorim/element-web:latest
    networks:
      as:
        ipv4_address: 120.0.16.12

  isp-b-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./data/isp-b-router:/data
    networks:
      as:
        ipv4_address: 120.0.16.3
      isp-b:
        ipv4_address: 120.0.24.2

  b1-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./data/b1-router:/data
    networks:
      isp-b:
        ipv4_address: 120.0.24.3

  isp-c-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./data/isp-c-router:/data
    networks:
      as:
        ipv4_address: 120.0.16.4
      isp-c:
        ipv4_address: 120.0.20.2

  c1-router:
    extends:
      file: ./docker-compose-common.yml
      service: box
    volumes:
      - ./data/c1-router:/data
    networks:
      isp-c:
        ipv4_address: 120.0.20.3
      priv-1:
        ipv4_address: 192.168.0.2

  c1-client:
    extends:
      file: ./docker-compose-common.yml
      service: client
    volumes:
      - ./data/c1-client:/data
    networks:
      priv-1:
        ipv4_address: 192.168.0.3

networks:
  as:
    ipam:
      config:
        - subnet: 120.0.16.0/22
  isp-b:
    ipam:
      config:
        - subnet: 120.0.24.0/21
  isp-c:
    ipam:
      config:
        - subnet: 120.0.20.0/22
  priv-1:
    ipam:
      config:
        - subnet: 192.168.0.0/24

volumes:
  matrix-server:
