services:
  as-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/as-router:/scripts # `init.sh` location
    networks:
      # networks attached to the container
      default: null # the default network, bridged to the host
      as:
        # `as` network defined in the `networks` section below
        ipv4_address: 120.0.16.2 # static IP

  b-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/b-router:/scripts
    networks:
      as:
        ipv4_address: 120.0.16.3
      businesses:
        ipv4_address: 120.0.24.2

  isp-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/isp-router:/scripts
    networks:
      as:
        ipv4_address: 120.0.16.4
      isp:
        ipv4_address: 120.0.20.2

  c1-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/c1-router:/scripts
    networks:
      isp:
        ipv4_address: 120.0.20.3

  c2-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/c2-router:/scripts
    networks:
      isp:
        ipv4_address: 120.0.20.4

networks:
  as:
    ipam:
      config:
        - subnet: 120.0.16.0/22
  isp:
    ipam:
      config:
        - subnet: 120.0.20.0/22
  businesses:
    ipam:
      config:
        - subnet: 120.0.24.0/21
