services:
  as-router:
    image: projet-interco/router
    build: ./dockerfiles/router
    container_name: as-router
    cap_add:
      - NET_ADMIN
    environment:
      - APP_NAME=as-router
    volumes:
      - ./scripts/as-router:/scripts
    ports:
      - 5800:5800
    networks:
      default:
      as:
        ipv4_address: 120.0.16.2

  b1-router:
    image: projet-interco/router
    build: ./dockerfiles/router
    container_name: b1-router
    cap_add:
      - NET_ADMIN
    environment:
      - APP_NAME=b1-router
    volumes:
      - ./scripts/b1-router:/scripts
    ports:
      - 5810:5800
    networks:
      as:
        ipv4_address: 120.0.16.4
      b1:
        ipv4_address: 120.0.24.2

  b2-router:
    image: projet-interco/router
    build: ./dockerfiles/router
    container_name: b2-router
    cap_add:
      - NET_ADMIN
    environment:
      - APP_NAME=b2-router
    volumes:
      - ./scripts/b2-router:/scripts
    ports:
      - 5820:5800
    networks:
      as:
        ipv4_address: 120.0.16.5
      b2:
        ipv4_address: 120.0.28.2

  ind-router:
    image: projet-interco/router
    build: ./dockerfiles/router
    container_name: ind-router
    cap_add:
      - NET_ADMIN
    environment:
      - APP_NAME=ind-router
    volumes:
      - ./scripts/ind-router:/scripts
    ports:
      - 5830:5800
    networks:
      as:
        ipv4_address: 120.0.16.3
      ind:
        ipv4_address: 120.0.20.2

  i1-router:
    image: projet-interco/router
    build: ./dockerfiles/router
    container_name: i1-router
    cap_add:
      - NET_ADMIN
    environment:
      - APP_NAME=i1-router
    volumes:
      - ./scripts/i1-router:/scripts
    ports:
      - 5840:5800
    networks:
      ind:
        ipv4_address: 120.0.20.3

  i2-router:
    image: projet-interco/router
    build: ./dockerfiles/router
    container_name: i2-router
    cap_add:
      - NET_ADMIN
    environment:
      - APP_NAME=i2-router
    volumes:
      - ./scripts/i2-router:/scripts
    ports:
      - 5850:5800
    networks:
      ind:
        ipv4_address: 120.0.20.4

networks:
  as:
    ipam:
      config:
        - subnet: 120.0.16.0/22
  ind:
    ipam:
      config:
        - subnet: 120.0.20.0/22
  b1:
    ipam:
      config:
        - subnet: 120.0.24.0/22
  b2:
    ipam:
      config:
        - subnet: 120.0.28.0/22
