services:
  as-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/as-router:/scripts # `init.sh` location
    networks:
      # networks attached to the container
      default: null # the default network, bridged to the host
      as:
        # `as` network defined in the `networks` section below
        ipv4_address: 120.0.16.2 # static IP

  b1-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/b1-router:/scripts
    networks:
      as:
        ipv4_address: 120.0.16.4
      b1:
        ipv4_address: 120.0.24.2

  b2-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/b2-router:/scripts
    networks:
      as:
        ipv4_address: 120.0.16.5
      b2:
        ipv4_address: 120.0.28.2

  ind-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/ind-router:/scripts
    networks:
      as:
        ipv4_address: 120.0.16.3
      ind:
        ipv4_address: 120.0.20.2

  i1-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/i1-router:/scripts
    networks:
      ind:
        ipv4_address: 120.0.20.3

  i2-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/i2-router:/scripts
    networks:
      ind:
        ipv4_address: 120.0.20.4

networks:
  as:
    ipam:
      config:
        - subnet: 120.0.16.0/22
  ind:
    ipam:
      config:
        - subnet: 120.0.20.0/22
  b1:
    ipam:
      config:
        - subnet: 120.0.24.0/22
  b2:
    ipam:
      config:
        - subnet: 120.0.28.0/22

