services:
  as-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./data/as-router:/data # `init.sh` location
    networks:
      # networks attached to the container
      as:
        # `as` network defined in the `networks` section below
        ipv4_address: 120.0.16.2 # static IP

  irc-server:
    image: ergochat/ergo:latest
    networks:
      as:
        ipv4_address: 120.0.16.10

  matrix-server:
    image: matrixdotorg/synapse:latest
    environment:
      - SYNAPSE_SERVER_NAME=AS1
      - SYNAPSE_REPORT_STATS=yes
    # command: generate   # uncomment to generate config
    # to register users: 
    # docker compose exec matrix-server register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml
    volumes:
      - matrix-server:/data
    networks:
      as:
        ipv4_address: 120.0.16.11

  matrix-web:
    image: vectorim/element-web:latest
    networks:
      as:
        ipv4_address: 120.0.16.12

  isp-entr-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./data/isp-entr-router:/data
    networks:
      as:
        ipv4_address: 120.0.16.3
      isp-entr:
        ipv4_address: 120.0.24.2

  entr1-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./data/entr1-router:/data
    networks:
      isp-entr:
        ipv4_address: 120.0.24.3
      entr1-dmz:
        ipv4_address: 120.0.28.2
      entr1-intra:
        ipv4_address: 120.0.29.2

  isp-user-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./data/isp-user-router:/data
    networks:
      as:
        ipv4_address: 120.0.16.4
      isp-user:
        ipv4_address: 120.0.20.2

  user1-router:
    extends:
      file: ./docker-compose-common.yml
      service: box
    volumes:
      - ./data/user1-router:/data
    networks:
      isp-user:
        ipv4_address: 120.0.20.3
      user1:
        ipv4_address: 192.168.0.2

  user1-client:
    extends:
      file: ./docker-compose-common.yml
      service: client
    volumes:
      - ./data/user1-client:/data
    networks:
      user1:
        ipv4_address: 192.168.0.3

networks:
  as:
    ipam:
      config:
        - subnet: 120.0.16.0/22
  isp-entr:
    ipam:
      config:
        - subnet: 120.0.24.0/21
  # Entreprises:
  # 120.0.28.0/22
  # |- 120.0.28.0/23  Entreprise 1
  #   |- 120.0.28.0/24  DMZ
  #   |- 120.0.29.0/24  Intranet
  # |- 120.0.30.0/23  Entreprise 2
  #   |- 120.0.30.0/24  DMZ
  #   |- 120.0.31.0/24  Intranet
  entr1-dmz:
    ipam:
      config:
        - subnet: 120.0.28.0/24
  entr1-intra:
    ipam:
      config:
        - subnet: 120.0.29.0/24
  isp-user:
    ipam:
      config:
        - subnet: 120.0.20.0/22
  user1:
    ipam:
      config:
        - subnet: 192.168.0.0/24

volumes:
  matrix-server:
