services:
  as-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/as-router:/scripts # `init.sh` location
      - ./scripts/as-router/quagga:/etc/quagga
    networks:
      # networks attached to the container
      as:
        # `as` network defined in the `networks` section below
        ipv4_address: 120.0.16.2 # static IP

  isp-b-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/isp-b-router:/scripts
      - ./scripts/isp-b-router/quagga:/etc/quagga
    networks:
      as:
        ipv4_address: 120.0.16.3
      isp-b:
        ipv4_address: 120.0.24.2

  b1-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/b1-router:/scripts
      - ./scripts/b1-router/quagga:/etc/quagga
    networks:
      isp-b:
        ipv4_address: 120.0.24.3

  isp-c-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/isp-c-router:/scripts
      - ./scripts/isp-c-router/quagga:/etc/quagga
    networks:
      as:
        ipv4_address: 120.0.16.4
      isp-c:
        ipv4_address: 120.0.20.2

  c1-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/c1-router:/scripts
      - ./scripts/c1-router/quagga:/etc/quagga
    networks:
      isp-c:
        ipv4_address: 120.0.20.3

  c2-router:
    extends:
      file: ./docker-compose-common.yml
      service: router
    volumes:
      - ./scripts/c2-router:/scripts
      - ./scripts/c2-router/quagga:/etc/quagga
    networks:
      isp-c:
        ipv4_address: 120.0.20.4

networks:
  as:
    ipam:
      config:
        - subnet: 120.0.16.0/22
  isp-b:
    ipam:
      config:
        - subnet: 120.0.24.0/21
  isp-c:
    ipam:
      config:
        - subnet: 120.0.20.0/22
